name: Trung
favicon: null
layout_spectrum: 0.00253
typography_spectrum: 0.25253
title: "Trung's Site"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffef9'
    - '#251d24'
    - '#a86b71'
    - '#d69b9b'
    - '#7e0421'
  brandStrength: 0.75
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
